name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_separate_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Use the PAT
        run: echo ${{ secrets.DEPLOYMENT_PAT }}
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create separate branch
        run: |
          git checkout -b main_clone_2
          git push origin main_clone_2

  deploy:
    runs-on: ubuntu-latest
    needs: [create_separate_branch]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "jeeva.e@avasoft.com"
          git config --global user.name "Ava-JeevaYovanE"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create File
        run: |
          echo "This is some content." > new_file.txt
          git add new_file1.txt
          git commit -m "Add new_file.txt"
          git push origin main
      - name: Build
        run: |
          echo "Build"
      - name: Deploy
        run: |
          echo "Deploy"
          exit 1

  Deploy_check:
    runs-on: ubuntu-latest
    needs: [deploy,create_separate_branch]
    if: failure() 
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Commands
        run: |
          git merge main_clone_2 --allow-unrelated-histories
          git push origin main
