name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  create_separate_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Use the PAT
        run: echo ${{ secrets.DEPLOYMENT_PAT }}
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create separate branch
        run: |
          git checkout -b main_clone_1
          git push origin main_clone_1

  deploy:
    runs-on: ubuntu-latest
    needs: [create_separate_branch]

    steps:
      - name: Deploy changes to production
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Build"
      - name: Deploy
        run: echo "Deploy"

  Deploy_check:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: ${{ needs.deploy.outputs.status }}== 'false'
    steps:
      - name: Commands
        run: |
          git checkout main_clone_1
          git checkout main
          git merge main_clone_1
          git push origin main
