name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  create_separate_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Use the PAT
        run: echo ${{ secrets.DEPLOYMENT_PAT }}
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create separate branch
        run: |
          git checkout -b main_clone
          git push origin main_clone

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy changes to production
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/git:v1
          if [ $? -ne 0 ]; then
            echo "Deployment failed. Creating separate branch."
            git checkout main_clone
            git checkout main
            git merge main_clone
            git push origin main
          fi
